server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /home/lb/ros2_ws/src/bumblebee/www;
    index gcs.html index.html;
    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
}
